services:
  web:
    build: .

    command:
      - uv
      - run
      - flask
      - --app
      - mediawiki_monitor.__main__:create_app
      - run
      - --host=0.0.0.0
      - --port=8000
      - --debug

    volumes:
      - .:/app
      - venv:/app/.venv

    ports:
      - "8000:8000"

volumes:
  venv:
